---
title: "Publications"
toc: true
---

This is an overview of my academic and non-academic publications, as well as ongoing work. You can also view them on my [Google Scholar](https://scholar.google.nl/citations?user=oFDW6tIAAAAJ) profile.

## Journal articles

Ergen, T., & **Schmitz, L**. (2025): Picking Losers: Climate Change and Managed Decline in the European Union. *Regulation & Governance*. [Paper](https://onlinelibrary.wiley.com/doi/10.1111/rego.70004).

**Schmitz, L**., Seidl, T. & Wuttke, T. (2025): The costs of conditionality. IPCEIs and the constrained politics of EU industrial policy. *Competition & Change*. [Paper](https://journals.sagepub.com/doi/10.1177/10245294251320675) \| [online appendix](https://journals.sagepub.com/doi/10.1177/10245294251320675#appendix).

Seidl, T., & S**chmitz, L**. (2024): Moving on not to fall behind? Technological sovereignty and the 'geo-dirigiste' turn in EU industrial policy. *Journal of European Public policy 31*(8). [Paper](https://www.tandfonline.com/doi/full/10.1080/13501763.2023.2248204) \| [replication materials](https://www.tandfonline.com/doi/suppl/10.1080/13501763.2023.2248204?scroll=top).

Di Carlo, D., & **Schmitz, L**. (2023): Europe First? The rise of EU industrial policy promoting and protecting the single market. *Journal of European Public Policy 30*(10). [Paper](#0).

**Schmitz, L**., & Seidl, T. (2023): As open as possible, as Autonomous as Necessary: Understanding the Rise of Open Strategic Autonomy in EU Trade Policy. *Journal of Common Market Studies* *61*(3). [Paper](#0).

**Schmitz, L**., & Eimer, T.R. (2020): From Coherence to Coheritization**:** explaining the rise of policy coherence in EU external policy. *Globalizations 17*(4). [Paper](https://www.tandfonline.com/doi/full/10.1080/14747731.2019.1676103).

## Book chapters

(with Andrea K. Gerlak and colleagues): Power(ful) and Power(less): A Review of Power in the ESG--Agency Scholarship. In M. Betsill, T. Benney, & A. Gerlak (Eds.), Agency in Earth System Governance (pp. 65-72). Cambridge: Cambridge University Press. [Chapter](https://www.cambridge.org/core/books/abs/agency-in-earth-system-governance/powerful-and-powerless-a-review-of-power-in-the-esgagency-scholarship/29D6B6636BC9230E45E0B20C5247CC3A).

## Working papers

Cova, J., & **Schmitz, L**. (2024): A primer for the use of classifier and generative large language models in social science research. *OSF Preprint*. [Paper](https://osf.io/preprints/osf/r3qng_v1) \| [replication materials](https://github.com/joshcova/LLMs-for-social-scientists/tree/main).

**Schmitz, L**., Seidl, T. & Wuttke, T. (2024): The Costs of Conditionality. IPCEIs and the Constrained Politics of EU Industrial Policy. *OSF preprint*. [Paper](https://osf.io/preprints/osf/f63gd).

Ergen, T., & **Schmitz, L** (2023): The Sunshine Problem. Climate Change and Managed Decline in the European Union. *MPIfG discussion paper 2023/6*. [Paper](https://pure.mpg.de/pubman/item/item_3559564_2/component/file_3559565/mpifg_dp23_6.pdf).

**Schmitz, L**., & Seidl, T. (2022): Protecting, Transforming, and Projecting the Single Market. Open Strategic Autonomy and Digital Sovereignty in the EU's Trade and Digital Policies. *OSF preprint*. [Paper](https://doi.org/10.31235/osf.io/wjb64).

## Work in progress

Discipline and Profits: Geopolitics and the Great Restructuring of the Firm. *Unpublished manuscript (available upon request)*.

Changing the Calculus: How Security Displaces Efficiency in Global Economics. *Unpublished manuscript*.

Fighting the Future: Mapping Corporate Responses to Climate Change. *Unpublished manuscript*.

## Media & miscellaneous

Backlash. *De Groene Amsterdammer*. [Interview](https://www.groene.nl/artikel/backlash).

De Europese markt heeft industriepolitiek op Europees niveau nodig. *NRC Handelsblad* (with Jasper H. van Dijk). Opinion piece ([paywalled](https://www.nrc.nl/nieuws/2023/03/12/de-europese-markt-heeft-industriepolitiek-op-europees-niveau-nodig-a4159212)).

As open as Possible, as Autonomous as Necessary -- Understanding the Rise of Open Strategic Autonomy. (with Timo Seidl). *Ideas on Europe Blog* [entry](https://jcms.ideasoneurope.eu/2022/11/03/as-open-as-possible-as-autonomous-as-necessary-understanding-the-rise-of-open-strategic-autonomy/).

Reflections on how COVID-19 is reshaping the EU's industrial strategy. *EUIdeas blog* [entry](https://euideas.eui.eu/2020/06/04/reflections-on-how-covid-19-is-reshaping-the-eus-industrial-strategy/).
